# Generated by Django 5.2.12 on 2026-09-30 18:20

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('certification_number', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('city', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vin', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator('^[A-HJ-NPR-Z0-9]{17}$', 'VIN must be 17 characters, excluding I, O, Q.')], verbose_name='VIN')),
                ('license_plate', models.CharField(max_length=20)),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1886)])),
                ('is_active', models.BooleanField(default=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='fleet.office')),
            ],
            options={
                'ordering': ('make', 'model', 'vin'),
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performed_on', models.DateField()),
                ('maintenance_type', models.CharField(choices=[('oil_change', 'Oil change'), ('tire_rotation', 'Tire rotation'), ('brakes', 'Brakes'), ('inspection', 'Inspection'), ('repair', 'Repair'), ('other', 'Other')], max_length=32)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.TextField(blank=True)),
                ('mechanic', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='fleet.mechanic')),
                ('vehicle', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='fleet.vehicle')),
            ],
            options={
                'ordering': ('-performed_on', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['make', 'model'], name='vehicle_make_model_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(models.F('license_plate'), condition=models.Q(('is_active', True)), name='uniq_active_vehicle_license_plate', violation_error_message='An active vehicle with this license plate already exists.'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('vin__regex', '^[A-HJ-NPR-Z0-9]{17}$')), name='vehicle_vin_format'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('license_plate', django.db.models.functions.text.Upper('license_plate'))), name='vehicle_license_plate_uppercase'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('year__gte', 1886)), name='vehicle_year_min'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['vehicle', '-performed_on'], name='maint_vehicle_date_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['mechanic', 'performed_on'], name='maint_mechanic_date_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['performed_on'], name='maint_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='maintenancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('cost__gte', 0)), name='maintenance_cost_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='maintenancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('maintenance_type__in', ['oil_change', 'tire_rotation', 'brakes', 'inspection', 'repair', 'other'])), name='maintenance_type_valid'),
        ),
    ]
