# Generated by Django 5.2.12 on 2026-09-30 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ('name', 'city')},
        ),
        migrations.RemoveConstraint(
            model_name='vehicle',
            name='vehicle_license_plate_uppercase',
        ),
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'License plate must contain only A-Z and 0-9.')]),
        ),
        migrations.AddConstraint(
            model_name='office',
            constraint=models.UniqueConstraint(models.F('name'), models.F('city'), name='uniq_office_name_city', violation_error_message='An office with this name already exists in this city.'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('license_plate__regex', '^[A-Z0-9]+$')), name='vehicle_license_plate_format'),
        ),
    ]
