# Generated by Django 5.2.12 on 2026-09-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_office_name_city_unique_plate_format'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='office',
            name='uniq_office_name_city',
        ),
        migrations.RemoveConstraint(
            model_name='vehicle',
            name='uniq_active_vehicle_license_plate',
        ),
        migrations.AddConstraint(
            model_name='office',
            constraint=models.UniqueConstraint(fields=('name', 'city'), name='uniq_office_name_city', violation_error_message='An office with this name already exists in this city.'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('license_plate',), name='uniq_active_vehicle_license_plate', violation_error_code='unique', violation_error_message='An active vehicle with this license plate already exists.'),
        ),
    ]
