# Generated by Django 5.2.12 on 2026-09-30 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_unique_constraints_use_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vehicle',
            name='vehicle_make_model_idx',
        ),
    ]
