# Generated by Django 5.2.12 on 2026-09-30 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_drop_vehicle_make_model_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='certification_number',
            field=models.CharField(error_messages={'unique': 'A mechanic with this certification number already exists.'}, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(error_messages={'unique': 'A vehicle with this VIN already exists.'}, max_length=17, unique=True, validators=[django.core.validators.RegexValidator('^[A-HJ-NPR-Z0-9]{17}$', 'VIN must be 17 characters, excluding I, O, Q.')], verbose_name='VIN'),
        ),
    ]
