# Generated by Django 5.2.12 on 2026-10-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_unique_error_messages'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['make', 'model', 'vin'], name='vehicle_list_order_idx'),
        ),
    ]
